---
# baseUrl: "http://jacknicholas.github.io/jrn-ebo-hugo/"
languageCode: "en-uk"
title: "jrn-ebo"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
builddraft: false
uglyUrls: true
# canonifyurls: true
MetaDataFormat: "yaml"
---
